@token = jwt_token

POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "title": "My first blog post",
  "author": "John Doe",
  "url": "https://example.com/my-first-blog-post",
  "likes": 0
}